branches:
  only:
    - master

sudo: required

language: python

services:
  - docker

before_script:
  - python --version
  - docker version
  - docker ps -a
  - docker build -t clarencep/demo-nodejs-addon-test-chan-via-golang .
  - docker images
  - docker ps -a

script:
  - docker run -it --rm clarencep/demo-nodejs-addon-test-chan-via-golang node /usr/src/node-addon-test-chan/test.js
